spring:
  application:
    name: transaction-aggregator

---
spring:
  config:
    activate:
      on-profile: docker
  devtools:
    restart:
      enabled: false
  docker:
    compose:
      enabled: false
