spring:
  application:
    name: transaction-aggregator
  jackson:
    default-property-inclusion: non_null

app:
  default-currency: GBP

---
spring:
  config:
    activate:
      on-profile: docker
  devtools:
    restart:
      enabled: false
  docker:
    compose:
      enabled: false
